const CONTRACT_PERWALLET_MAX_MINT_AMOUNT= 10;
const CONTRACT_NFT_TOTAL_AMOUNT= 5555;
const CONTRACT_NFT_PER_PRICE= 0.001;
const FREE_MINT_AMOUNT= 1000;
const CONTRACT_NFT_OFFICIAL_NAME= "Tocabo";
const CONTRACT_NFT_SAMBLE_NAME= "TOCABO";
const CONTRACT_STATUS = {
  'OFF': '0',
  'ON': '1',
  'SOLD_OUT': '2',
}
const SOCIAL_MEDIA_URL = {
  'OPENSEA': 'https://opensea.io/collection/tocabo',
  'DISCORD': 'https://discord.com/invite/NqtRrGbQDr',
  'TWITTER': 'https://twitter.com/TocaIsland',
}

export {
  CONTRACT_PERWALLET_MAX_MINT_AMOUNT,
  CONTRACT_NFT_TOTAL_AMOUNT,
  CONTRACT_NFT_PER_PRICE,
  CONTRACT_STATUS,
  SOCIAL_MEDIA_URL,
  CONTRACT_NFT_OFFICIAL_NAME,
  CONTRACT_NFT_SAMBLE_NAME,
  FREE_MINT_AMOUNT
}